[[section-architecture-constraints]]
== Constraints


****
|===
|Constraint |Background and / or motivation

|Third party software must be
available under an compatible
open source license and
installable via a package
manager
|The interested developer or
architect should be able to
check out the sources, compile
and run the application
without problems compiling
or installing dependencies. All
external dependencies should
be available via the package
manager of the operation
system or at least through an
installer.

|Build system
|Gradle as build system to compare with maven

|OS independent development
|The application should be
compilable on all 3 mayor
operation systems (Mac OS X,
Linux and Windows)

|Deployable to a Linux server
|The application should be
deployable through standard
means on a Linux based server

|Memory friendly
|Memory can be limited (due to
availability on a shared host or
deployment to cloud based
host). If deployed to a cloud
based solution, every
megabyte of memory costs.

|Published under an Open Source license
|The source, including
documentation, should be
published as Open Source
under the Apache 2 License.


|===
****